# Logo Url
# Please enter the absolute path to your logo file
# or remove the following line with replacing logo-header.png with your own logo
logo: https://dn-myblog.qbox.me/logo-header.png

# Header
menu:
  Home: /
  # Delete this row if you don't want categories in your header nav bar
  Categories:
  LeetCode: /LeetCode/
  About: /about/

# Article list grouped by year
groupByYear: true

# Content
fancybox: true

# Thumbnail
thumbnail: true

# Scroll Loading
scrollLoading: true

# Sidebar
sidebar: right // sidebar's position (left or right)
social_links:
  twitter:
  facebook:
  google_plus:
  github: https://github.com/zhouhao
  weibo:
  rss: /atom.xml
widgets:
- recent_posts
- category
- archive
- tagcloud
- links

# Links
links:
  Hexo: http://hexo.io

# Don't Use Google APIs if you are in google-blocked areas
use_google_apis: false

# Miscellaneous
google_analytics: UA-39886095-1
favicon: /favicon.png
fb_admins:
fb_app_id:
