menu:
  Home: /
  LeetCode(Java): /LeetCode/
# Archives: /archives

widgets:
- search
- google_translate
- about_me
- category
- tagcloud
- link

excerpt_link: "Read More"

twitter:
  username: sbzhouhao
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid: ra-5381610928f9a751
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-39886095-1
rss:

comment_provider: disqus
# Facebook comment
facebook:
  appid: 737433472988132
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light

links:
- name: "MIT-CHIEF"
  link: http://mitchief.org
- name: "WPILIFE (WPI CSSA)"
  link: http://wpilife.org
- name: "Free Twitter Keywords"
  link: http://freetwitterkeywords.com
- name: My Marriage
  link: http://marriage.hzhou.me

donate:
  title: Buy Me A Coffee
  paypal_merchant_ID: G7W4WVY32HXYS

about_me:
  title: "About Me"
  avatar: royhzhou@gmail.com
  texts:
  - GitHub：<a href="https://github.com/zhouhao" target="_blank">zhouhao</a>
  - LinkedIn：<a href="http://www.linkedin.com/in/sbzhouhao/" target="_blank">Hao Zhou</a>
  - 'Email: <a href="mailto:&#105;&#064;&#104;&#122;&#104;&#111;&#117;&#046;&#109;&#101;">&#105;&#064;&#104;&#122;&#104;&#111;&#117;&#046;&#109;&#101;</a>'
