fancybox: true ## If you want to use fancybox please set the value to true
duoshuo: ## Your duoshuo_shortname, e.g. haomwei
disqus: zhouhao ## Your disqus_shortname, e.g. haomwei
menu:
  - page: home
    directory: /
    icon: icon-home
  - page: archive
    directory: archives/
    icon: icon-archive
  - page: about
    directory: about/
    icon: icon-about
  - page: LeetCode
    directory: LeetCode/
    icon: icon-history
## links:
##   - title: site-name1
##     url: http://www.example1.com/
##   - title: site-name2
##     url: http://www.example2.com/
##   - title: site-name3
##     url: http://www.example3.com/
highlight:
  enable: true
  auto_detect: true
  line_number: true
  tab_replace: