# Header
menu:
  待填坑: /todo
  留言板: /about
  RSS: /atom.xml

# Content
excerpt_link: Read More
prev: Prev
next: Next
reply: 评论
share: 分享
fancybox: true

# Sidebar
widgets:
- search
- about
- recent_posts
- archive
- category
- tagcloud

# Miscellaneous
google_analytics:
disqus_shortname: zhouhao
rss: /atom.xml
favicon: /favicon.png
google_site_verification: NCXVSqxqB-os803-VFMtIEd1SUNJVOIjctCfNYUwD0w
baidu_site_verification: Nzwx7HuplM
